// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "get_posts", input: string, result: any } | 
        { key: "get_repos", input: string, result: any } | 
        { key: "greet", input: string, result: string },
    mutations: never,
    subscriptions: never
};
